services:
  postgres:
    image: postgres:16
    container_name: cloudswitch-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudswitch
    ports:
      - "5432:5432"
    volumes:
      - cloudswitch_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cloudswitch-redis
    ports:
      - "6379:6379"

  backend:
    image: cloudswitch-backend:test
    container_name: cloudswitch-backend
    env_file:
      - .env 
    ports:
      - "3000:3000"
volumes:
  cloudswitch_postgres_data: